services:
  - type: web
    name: transpareneats-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    routes:
      - type: rewrite
        source: /admin
        destination: /admin/index.html
      - type: rewrite
        source: /admin/analytics
        destination: /admin/analytics.html
    buildFilter:
      paths:
        - backend/**/*
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 