services:
  - type: web
    name: transpareneats-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: transpareneats-db
          property: connectionString
    routes:
      - type: rewrite
        source: /admin
        destination: /admin/index.html
      - type: rewrite
        source: /admin/analytics
        destination: /admin/analytics.html
    buildFilter:
      paths:
        - backend/**/*
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true

  # Frontend web app
  - type: web
    name: transpareneats-web
    env: node
    buildCommand: cd web && npm install && npm run build
    startCommand: cd web && npm start
    envVars:
      - key: VITE_BACKEND_URL
        value: https://transpareneats-api.onrender.com

databases:
  - name: transpareneats-db
    databaseName: transpareneats
    user: transpareneats
    plan: free

# Add this section to run migrations after deploy
hooks:
  postDeploy:
    - path: backend/scripts/run-migrations.js
      command: cd backend && npm run migrate:prod 