services:
  - type: web
    name: transpareneats-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: transpareneats-db
          property: connectionString
      - key: PORT
        value: 3000

databases:
  - name: transpareneats-db
    plan: free 